CREATE TABLE departamentos (
id SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
nome VARCHAR(50) NOT NULL,
sigla VARCHAR(5) NOT NULL,
responsavel VARCHAR(50) NOT NULL
);

CREATE TABLE funcionarios (
id SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
nome VARCHAR(50) NOT NULL,
endereco VARCHAR(100) NOT NULL,
telefone BIGINT NOT NULL,
cargo VARCHAR(25) NOT NULL,
salario DECIMAL(7,2) NOT NULL,
FOREIGN KEY (id) references departamentos(id)
);

CREATE TABLE dependentes (
id SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
nome VARCHAR(50) NOT NULL,
idade TINYINT NOT NULL,
tipo VARCHAR(15) NOT NULL,
status_dep VARCHAR(10) NOT NULL,
FOREIGN KEY (id) REFERENCES funcionarios(id)
);